name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 20.2.36 
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.0
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0
  intl: ^0.17.0
  
  syncfusion_localizations: ^20.2.36
  syncfusion_flutter_datagrid_export: ^20.2.36-beta
  syncfusion_flutter_calendar: ^20.2.36
  syncfusion_flutter_datepicker: ^20.2.36
  syncfusion_flutter_charts: ^20.2.36
  syncfusion_flutter_gauges: ^20.2.36
  syncfusion_flutter_sliders: ^20.2.36
  syncfusion_flutter_pdf: ^20.2.36
  syncfusion_flutter_barcodes: ^20.2.36
  syncfusion_officechart: ^20.2.36-beta
  syncfusion_flutter_maps: ^20.2.36
  syncfusion_flutter_signaturepad: ^20.2.36
  syncfusion_flutter_pdfviewer: ^20.2.36-beta
  syncfusion_flutter_treemap: ^20.2.36-beta

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - images/pdf_viewer/
    - assets/pdf/
    - lib/sample_details.json
    - world_map.json
    - africa.json
    - europe.json
    - germany.json
    - india.json
    - usa.json
    - south_america.json
    - australia.json
    - maps_brazil_boundary.json
    - maps_uk_boundary.json
    - maps_france_boundary.json
    - river.json
    - london_to_british.json
    - london_to_chessington.json
    - london_to_hampton_court_palace.json
    - london_to_twickenham_stadium.json
    - london_to_windsor_castle.json
    - product_data.json
    - chart_data.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
